#!/bin/bash

# Variable values explored by benchmark.sh
N_VALUES=(50000000)
P_VALUES=(256)
SEED_VALUES=(13)
MAX_KEY_VALUES=(1000000)
PARTITION_THREAD_VALUES=(1)
JOIN_THREAD_VALUES=(1)

# Unused parameters for the sequential version
PARTITION_SCHEDULE_VALUES=(auto)
JOIN_SCHEDULE_VALUES=(auto)
PARTITION_CHUNK_VALUES=(0)
JOIN_CHUNK_VALUES=(0)
PARTITION_BLOCK_SIZE_VALUES=(32768)